### PR TITLE
Add support for assumed_role and STS

### PR DESCRIPTION
**Pull request by ShimiTaNaka**
Add support to get assumed_role credentials and add option to set default STS TTL and max STS TTL

### CODE REVIEW

**Comment by ShimiTaNaka** [comment]
I have ran tests and acceptance tests against Vault 1.1.0 without AWS keys, so some of the tests didn't pass.
Would be happy to know if there are scenarios in which the tests fail.

**Comment by ShimiTaNaka** [comment]
@tyrannosaurus-becks I'll get on it

**Comment by ShimiTaNaka** [comment]
@tyrannosaurus-becks Looking Again on my changes, since I took another PR that wasn't maintained, I didn't notice I'm also adding the `role_arns`
Since there are few relatively important differences, I suggest having another pair of eyes
(For example, now in master, `policy` is marked as conflicting with `role_arns`, however, I do not see any evidence for it in the documentation, contrary, it seems that you can add both and have the `policy` as extra filter in addition to the roles
This obviously also affects the rest of the code. 
@oxlay Would love your input as well since the conflicting PR is yours if possible :)
Thanks

**Comment by ShimiTaNaka** [comment]
@tyrannosaurus-becks any updates?

**Comment by tyrannosaurus-becks** [comment]
Happy to take a look at this once master is merged in!

**Comment by loslocostacos** [comment]
It appears that this has been resolved via #444

**Comment by tyrannosaurus-becks** [comment]
Closing this for now due to inactivity. If you end up wanting to reopen this, feel free to do so when you're ready. Thank you for your work!

**Pull request closed without merging**
