### PR TITLE
Upgrade to Terraform 0.12

### PR DESCRIPTION
**Pull request by cvbarros**
Based on [Terraform 0.12 Compatibility for Providers](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html), I couldn't find anything blocking for the upgrade.

This PR was just prepared doing

```
> GO111MODULE=on go get github.com/hashicorp/terraform@v0.12.0
```

To grab the 0.12 Terraform release - All the acceptance tests that could have been ran locally passed without problems.

### CODE REVIEW

**Comment by cvbarros** [comment]
Resolves #424 after a new release is cut by Hashicorp [if metadata is placed](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#releasing-the-updated-provider)

**Comment by pschulten** [comment]
thanks @cvbarros I ran your patch against master  but get `Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`
Am I missing something?

**Comment by cvbarros** [comment]
@pschulten how exactly? You built from source and then tried to use the provider live with Terraforn 0.12?

**Comment by pschulten** [comment]
@cvbarros I,
1. pulled from from master https://github.com/terraform-providers/terraform-provider-vault
2. applied your changes ` curl -s https://patch-diff.githubusercontent.com/raw/terraform-providers/terraform-provider-vault/pull/425.patch | git apply -v  --index
`
3. `make build`
4. copied the output to ~/.terraform.d/plugins/terraform-provider-vault_v1.9.0
5. use  the plugin  with `provider vault {
  version = ">= 1.9.0"
  address = "${local.vault_addr}"
}`

**Comment by pschulten** [comment]
@cvbarros ignore me, maybe I had a stale local state, did the things from above in a clean env and everything works. Sorry for my noise :(

**Comment by roidelapluie** [comment]
your PR misses `go mod vendor`

**Comment by cvbarros** [comment]
> your PR misses `go mod vendor`

Nice, @roidelapluie , totally forgot it! Thanks for the review, updated it.

**Comment by e96wic** [comment]
It looks like everything is ready to merge, any updates on this?

**Comment by nyurik** [comment]
Any blockers for this?  cc: @tyrannosaurus-becks 
thx!!!

**Comment by cvbarros** [comment]
It will be reviewed in due time, until then we wait 👍 . PRs/issues are addressed in a [periodic basis](https://github.com/terraform-providers/terraform-provider-vault/blob/master/.github/CONTRIBUTING.md).

**Comment by eboumendil** [comment]
Quick question, how often do you guys address PRs/issues?

**Comment by tyrannosaurus-becks** [comment]
@cvbarros thanks for working on this! 

Paddy has been working on this as well on [this branch](https://github.com/terraform-providers/terraform-provider-vault/compare/0.12-sdk), which has a couple of additional changes. 

I'm going to do a quick release of where the provider is _before_ the change, and then circle back to this right afterwards this week and possibly do a second release to get support out for Terraform 0.12.

**Comment by anasinnyk** [comment]
@tyrannosaurus-becks it will be awesome if you can tag this branch like (v1.9.0-alpha) and we can use it immediately. Thanks.

**Comment by fabiendelpierre** [comment]
I'm not an enterprise customer, but if I was (and we are seriously considering it), I'd be super miffed that there is no support for Vault in TF 0.12. Since we depend on that provider for almost everything, this is blocking all of our 0.12 development. As both Terraform and Vault are Hashicorp products, this should have been available at the same time as TF 0.12.

I'm not blaming the maintainers of this provider in particular, just Hashicorp as an organization for dropping the ball.

**Comment by paultyng** [comment]
Closing this for the work being handled in the [0.12-sdk](https://github.com/terraform-providers/terraform-provider-vault/compare/0.12-sdk), progress can be tracked in issue #424.

**Pull request closed without merging**
