### PR TITLE
Vendor Vault API v0.11.0

### PR DESCRIPTION
**Pull request by jeff-jk**
This commit vendors the Vault API from the v0.11.0 tag.

### CODE REVIEW

**Comment by jeff-jk** [comment]
Due to breaking changes in in `Vault v0.11.0` (around sys the previously vendored API in this provider will no longer work against `Vault v0.11.0` when Terraform code contains a `vault_policy` resource. 

The following error will be thrown: ```vault_policy.policy: error reading from Vault: rules not found in response```

I haven't had to the opportunity to dig too deeply into the breaking changes yet but I'd imagine this is related to the sys/ top level injection removal and changes in sys_policy [[1](https://github.com/hashicorp/vault/commit/d9fa7636acfa9a38d7107d35d4d5b0f67ae7d96f#diff-a37f0378df74ff229c085460e7206e1fL55)]. 

@catsby @radeksimko @paddycarver sorry to bother, but could you or another maintainer please take a look at this PR and consider a minor or patch release? I'm currently working off of my own build of this provider as a workaround. I also created #164 in case we'd need to release a version of `terraform-provider-vault` that has `Vault API v0.10.4`.

1. https://github.com/hashicorp/vault/commit/d9fa7636acfa9a38d7107d35d4d5b0f67ae7d96f#diff-a37f0378df74ff229c085460e7206e1fL55

**Comment by cvbarros** [comment]
Upgrading Vault to 0.11 broke our terraform configuration (policies).

**Comment by woohgit** [comment]
Yeah, same here. v0.11 is not compatible with the latest terraform provider (v1.1.1).

**Comment by sc7565** [comment]
Upgrading vault broke the policies, @catsby can you verify this PR and merge this

**Comment by jeff-jk** [comment]
Temporary workaround is to build from the branch and place the binary in the `.terraform.d/plugins directory` so it's used in lieu of downloading the provider with the old API vendored:
```mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers && \
git clone https://github.com/jeff-jk/terraform-provider-vault vault-api-0.11.0 -b vault-api-0.11.0 && \
cd $GOPATH/src/github.com/terraform-providers/terraform-provider-vault && \
make build && \
mkdir -p $HOME/.terraform.d/plugins; cp $GOPATH/bin/terraform-provider-vault $HOME/.terraform.d/plugins/terraform-provider-vault
```

**Comment by catsby** [comment]
Hello –

Can someone verify that `v0.11.1` of vault resolves these issues? https://github.com/hashicorp/vault/pull/5244 was added after `v0.11.0` and shipped in `v0.11.1` to address issues like these

**Comment by cvbarros** [comment]
@catsby I can confirm this works for your Terraform using the current Vault provider version. Tested using docker image for Vault 0.11.1

**Comment by catsby** [comment]
@cvbarros great, thank you. We hope to update the Vault dependencies soon, it may or may not be this PR though, will update here when something changes

**Comment by tyrannosaurus-becks** [comment]
@jeff-jk thank you so much for this PR! Care and feeding of this repo recently went through a transition, and things will start to get moving again. 

We decided to skip straight ahead to vendoring Vault 0.11.1 because it had a fix for the issues it introduced in 0.11.0. I'm going to go ahead and close this for that reason, but again, your contribution is much appreciated.

**Pull request closed without merging**
