### PR TITLE
Support for namespaces

### PR DESCRIPTION
**Pull request by sergeytrasko**
PR for #175

### CODE REVIEW

**Comment by DawtCom** [comment]
Any ideas when this pull request will be merged?

**Comment by chrishoffman** [comment]
Thanks!

**Comment by toddmichael** [comment]
Should this work or is there still a missing piece?  I built from `master` and tried, but it fails with `permission denied`

### Fails with Terraform
```
$ ec terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
...
...
vault_mount.transit: Creating...
  accessor:                  "" => "<computed>"
  default_lease_ttl_seconds: "" => "<computed>"
  description:               "" => "transit secrets engine (aka encryption-as-a-servie)"
  max_lease_ttl_seconds:     "" => "<computed>"
  path:                      "" => "transit"
  type:                      "" => "transit"

Error: Error applying plan:

1 error(s) occurred:

* vault_mount.transit: 1 error(s) occurred:

* vault_mount.transit: error writing to Vault: Error making API request.

URL: POST https://vault.dev.##REDACTED##/v1/sys/mounts/transit
Code: 403. Errors:

* 1 error occurred:
	* permission denied
...
...
```

# Works with CLI
```
$ ec printenv VAULT_NAMESPACE
dev
$ ec vault secrets enable transit
Success! Enabled the transit secrets engine at: transit/
```

Saw the merge and thought perhaps I could use it as-is.  Perhaps I'm being presumptuous.

**Comment by b4b4r07** [comment]
I faced the similar situation with this error.

## Fails with Terraform

```console
$ ls /root/.terraform.d/plugins/
terraform-provider-vault_v1.4.2-custom
```

```hcl
provider "vault" {
  address   = "https://vault.dev.our_company.com:8200"
  token     = "s.xxx"
  namespace = "microservices/our_service_A"
}
```

```
data.vault_generic_secret.cert_asterisk_our_company_com_2018: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.vault_generic_secret.cert_asterisk_our_company_com_2018: 1 error(s) occurred:

* data.vault_generic_secret.cert_asterisk_our_company_com_2018: data.vault_generic_secret.cert_asterisk_our_company_com_2018: no secret found at "secret/cert_asterisk_our_company_com_2018/"
```

## Works with CLI

```console
$ vault read secret/cert_asterisk_our_company_com_2018
Key                 Value
---                 -----
refresh_interval    768h
crt                 xxx
pem                 xxx
```

**Comment by sergeytrasko** [comment]
I was able to reproduce the issue - not sure how it slipped during initial testing. 
The root cause is that child token that is used by Terraform was created for specified namespace. As result it had wrong policies assigned.
I will submit one more PR shortly.

**Comment by toddmichael** [comment]
Works like a charm.  Thanks so much for implementing this.  Huge win to me.  Cheers.

**Comment by b4b4r07** [comment]
>I was able to reproduce the issue - not sure how it slipped during initial testing.
The root cause is that child token that is used by Terraform was created for specified namespace. As result it had wrong policies assigned.
I will submit one more PR shortly.

Nice! Thank you! I'll check it later.

BTW when will these change be release?

**Pull request merged**
