### PR TITLE
removed conflicts between inline policy and policy_arns, updated tests

### PR DESCRIPTION
**Pull request by mliang2**
It's ok to have `policy_document` and `policy_arns` defined at the same time for the `vault_aws_secret_backend_role` provider. 

CLI equalivent:
```
vault write aws/roles/foo credential_type=iam_user policy_document=@iam.json policy_arns=arn:aws:iam::123456789012:policy/policy1,arn:aws:iam::123456789012:policy/policy2
```

### CODE REVIEW

**Comment by mliang2** [comment]
Looks I'm missing some tests, I'll fix that

**Comment by mliang2** [comment]
Are there any concerns on getting this merged? Would really like to get this done. 
Thx!

**Comment by tyrannosaurus-becks** [comment]
Hi @mliang2 ! I see you're right that they can be provided together, thanks for catching this.

When I run the tests against the current branch of Vault master, I get this:
```
=== RUN   TestAccAWSSecretBackendRole_basic
--- FAIL: TestAccAWSSecretBackendRole_basic (0.00s)
    testing.go:538: Step 0 error: Error loading configuration: Error parsing /tmp/tf-test741671546/main.tf: At 24:21: error parsing list, expected comma or list end, got: IDENT
=== RUN   TestAccAWSSecretBackendRole_import
--- FAIL: TestAccAWSSecretBackendRole_import (0.00s)
    testing.go:538: Step 0 error: Error loading configuration: Error parsing /tmp/tf-test998350737/main.tf: At 24:21: error parsing list, expected comma or list end, got: IDENT
=== RUN   TestAccAWSSecretBackendRole_nested
--- FAIL: TestAccAWSSecretBackendRole_nested (0.00s)
    testing.go:538: Step 0 error: Error loading configuration: Error parsing /tmp/tf-test467045820/main.tf: At 24:21: error parsing list, expected comma or list end, got: IDENT
FAIL
```
Can you post the version of Vault you're testing again, as well as the test output you're seeing for these?

**Comment by mliang2** [comment]
@tyrannosaurus-becks 
I used the same test method as used by the CI/CD to test the PRs; so I'm using Vault provided by the docker compile file in the root of the source code (`docker-compose.yaml`).  According to the docker compose file, it's `image: vault:1.0.0`

```
$ pwd
/home/ubuntu/go/src/github.com/terraform-providers/terraform-provider-vault
$ export VAULT_ADDR=http://localhost:8200
$ export VAULT_TOKEN=TEST
$ make testacc
<snip>

=== RUN   TestFlattenAuthMethodTune
--- PASS: TestFlattenAuthMethodTune (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-vault/vault   31.080s
```

**Comment by mliang2** [comment]
My fork was out of date w/ master.  Once I synced w/ master, `make testacc` passed with Vault 1.0.0 and 1.1.0

**Comment by mliang2** [comment]
FYI, here's how I tested w/ v1.1.0
```
$ export VAULT_DEV_ROOT_TOKEN_ID=TEST

$ export VAULT_ADDR=http://localhost:8200

$ export VAULT_TOKEN=TEST

$ ./vault --version
Vault v1.1.0 ('36aa8c8dd1936e10ebd7a4c1d412ae0e6f7900bd')

$ ./vault server -dev > vault.log 2>&1 &

$ go clean -testcache

$ make testacc

$ killall vault
```

**Comment by mliang2** [comment]
Turns out I was not testing w/ my AWS key set, so those tests were skipped; I'll look into how I can fix this

**Comment by mliang2** [comment]
@tyrannosaurus-becks This errors you're seeing should fixed.  It was caused by me putting the wrong order of the `sprintf` items.  (putting ARNs variables into the `policy_document` field instead of `policy_arns`.  Tested w/ Vault 1.0.0 and 1.1.0 and here's what I got w/ regards to the failed test you were seeing:

```
=== RUN   TestAccAWSSecretBackendRole_basic
--- PASS: TestAccAWSSecretBackendRole_basic (0.15s)
=== RUN   TestAccAWSSecretBackendRole_import
--- PASS: TestAccAWSSecretBackendRole_import (0.10s)
=== RUN   TestAccAWSSecretBackendRole_nested
--- PASS: TestAccAWSSecretBackendRole_nested (0.16s)
```

**Comment by mliang2** [comment]
On an unrelated notes `TestV2Secret` is failing on Vault 1.1.0  b/c on 1.1.0, `secret/` k/v is not mounted by default.

```
=== RUN   TestV2Secret
--- FAIL: TestV2Secret (0.05s)
    testing.go:538: Step 1 error: Error refreshing: 1 error(s) occurred:

        * data.vault_generic_secret.test: 1 error(s) occurred:

        * data.vault_generic_secret.test: data.vault_generic_secret.test: no secret found at "secret/foo"
```

**Pull request merged**
