### PR TITLE
Fix #98: Support Vault token helper.

### LINKED ISSUE #98: Support for the Vault token_helper
Hi,

Please support the Vault token_helper as a way to provide a token to the vault provider.
 
### Terraform Version
Terraform v0.11.7
+ provider.template v1.0.0
+ provider.vault v1.1.0

### Affected Resource(s)
- provider vault 

### Terraform Configuration Files
```hcl
provider "vault" {}
```

### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.vault: No vault token found: open /Users/<User>/.vault-token: no such file or directory
```

### Expected Behavior
To succesfuly provision resources in vault by retrieving a vault_token from the token_helper specified in my ~/.vault config file.

### Steps to Reproduce
1. Configure a vault token_helper in ~/.vault [(vault-token-helper.sh)](https://gist.github.com/tristanmorgan/af6f82c58196481fc77915abbe83e931)
2. `terraform apply`

### PR DESCRIPTION
**Pull request by jgiles**
Rather than manually pulling a Vault token from ~/.vault-token, use
Vault's DefaultTokenHelper. This will use the token helper configured at
~/.vault (or at VAULT_CONFIG_PATH), falling back to ~/.vault-token.

### CODE REVIEW

**Comment by jgiles** [comment]
@paddycarver this fixes #98.

I've tested it locally, but there wasn't a great spot to work it into the current acceptance tests.

See also https://github.com/hashicorp/vault/issues/4688, but we're having trouble with this currently so I figured I'd go ahead and put the fix in here.

**Comment by jgiles** [comment]
@paddycarver ping?

**Comment by jgiles** [comment]
@catsby @paddycarver @bflad @fatmcgav any chance of eyes on this? We're considering running our own fork at this point - token helper support is huge for us.

**Comment by tyrannosaurus-becks** [comment]
@jgiles absolutely! Just working my way through the backlog oldest first. Apologies for the _huge_ delay in getting to this. The provider was in transition from the Terraform team to the Vault team. I should be able to review this this week.

**Comment by jgiles** [comment]
That's great news @tyrannosaurus-becks ! The Vault team seems like an excellent home for this - we do our Vault configuration almost exclusively through Terraform, and we're excited to help improve the tool.

**Comment by jgiles** [comment]
Will do, @tyrannosaurus-becks - hopefully in the next couple days.

**Comment by jgiles** [comment]
Thanks for reviewing + merging @tyrannosaurus-becks ! Do you know when you might cut the next release?

**Pull request merged**
