### PR TITLE
Stop terraform wanting to reset mount TTLs back to zero

### PR DESCRIPTION
**Pull request by wjam**
This fixes issue #5 

Unfortunately, there doesn't appear to be an API to retrieve the default TTLs

### CODE REVIEW

**Comment by wjam** [comment]
Is there any chance of getting this PR merged? I'm interested in making further changes to the provider (#7) and wondering on whether they'd get merged. @apparentlymart @radeksimko

**Comment by apparentlymart** [comment]
Hi @wjam! Sorry for the lack of response here. The team is currently spending lots of energy on the forthcoming 0.10 release so we've been a bit neglectful of the provider repositories. :confounded: 

Given that `0` is a special value meaning "use the system default", the usual way this would be represented in Terraform is to declare the attribute in question to be both `Optional` _and_ `Computed`. This has a special meaning where Terraform will only consider this attribute for diff if it's present in the config, so you'd then be able to omit the value in config to accept the default but still be able to access the defaulted value for interpolation. I'd suggest using this approach unless there's a good reason why not, since it'll be more consistent with how similar things behave on other providers.

Thanks for working on this!

**Comment by wjam** [comment]
Hi @apparentlymart, I've updated the PR with the changes recommended. I've also raised #8 to allow Okta auth backends to be configured within Terraform

**Comment by apparentlymart** [comment]
Thanks for this, @wjam. Looks good to me!

**Pull request merged**
