### PR TITLE
Fix for issue #368 in which a namespace needs to be set before setting a child token

### PR DESCRIPTION
**Pull request by loslocostacos**
Possible resolution for #368

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
Just a note that this needs tests before reviewing and merging it to make sure it does what it intends. See [contributing](https://github.com/terraform-providers/terraform-provider-vault/blob/master/.github/CONTRIBUTING.md) for more.

Thanks for working on this!

**Comment by knoxor** [comment]
Is there a timeline for getting this fix released ?

**Comment by conorjduggan** [comment]
Ya it'd be brilliant to get this merged quickly please!

**Comment by jtcressy** [comment]
I have a more complete PR at #415 that includes tests and documentation. 
@tyrannosaurus-becks could you take a look and see if there's anything else I need to do so it can be ready for review?

**Comment by HridoyRoy** [comment]
@tyrannosaurus-becks wondering what the timeline for this fix is?

**Comment by loslocostacos** [comment]
Closing in preference to #415

**Pull request closed without merging**
