### PR TITLE
Add identity entity

### PR DESCRIPTION
**Pull request by gpiper14**
add a resource entry for `identity_entity`  and `identity_entity_alias`

### CODE REVIEW

**Comment by cvbarros** [comment]
Hi @gpiper14 , I believe this feature is already being implemented in another open pr #247, which is closer to being merged.

**Comment by tyrannosaurus-becks** [comment]
@gpiper14 indeed those does appear to be a dupe of #247 which did end up getting merged today. Thank you so much for working on this, though, the code and approach are very sound.

This PR _does_ have docs that weren't included in the other PR. Would you rather close this PR or merge in master and update the docs to match the merged code and let it stand?

**Comment by gpiper14** [comment]
I can merge in master and just include the docs

**Comment by gpiper14** [comment]
Updated to only contain docs

**Pull request merged**
