### PR TITLE
:alien: update vendor folder using govendor

### PR DESCRIPTION
**Pull request by dhohengassner**
use terraform v0.11.11 as vendor folder
this add possibility to use the current terraform guidelines for developing provider

for instance this is needed for the deprecation of an old resource
used in https://github.com/terraform-providers/terraform-provider-vault/pull/273

currently tests are failing on provider test with

```
» make test                                                                                                                                                                              dh@Davids-Mac-Pro
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
                xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-vault github.com/terraform-providers/terraform-provider-vault/util github.com/terraform-providers/terraform-provider-vault/vault
?       github.com/terraform-providers/terraform-provider-vault [no test files]
ok      github.com/terraform-providers/terraform-provider-vault/util    (cached)
--- FAIL: TestProvider (0.01s)
    provider_test.go:45: err: 4 error(s) occurred:
        
        * resource vault_identity_entity: id is a reserved field name
        * resource vault_identity_group_alias: id is a reserved field name
        * resource vault_identity_entity_alias: id is a reserved field name
        * resource vault_identity_group: id is a reserved field name
2019/03/05 16:18:42 [INFO] Found Vault Auth Backend state v0; migrating to v1
2019/03/05 16:18:42 [DEBUG] Attributes before migration: map[string]string{"path":"github-123/", "type":"github"}
2019/03/05 16:18:42 [DEBUG] Attributes after migration: map[string]string{"path":"github-123/", "type":"github"}:
2019/03/05 16:18:42 [INFO] Found Vault Generic Secret state v0; migrating to v1
2019/03/05 16:18:42 [DEBUG] Attributes before migration: map[string]string{"allow_read":"true", "data_json":"{\"hello\": \"world\"}", "path":"secret/test-123"}
2019/03/05 16:18:42 [DEBUG] Attributes after migration: map[string]string{"allow_read":"true", "data_json":"{\"hello\": \"world\"}", "path":"secret/test-123"}:
2019/03/05 16:18:42 [INFO] Found Vault Generic Secret state v0; migrating to v1
2019/03/05 16:18:42 [DEBUG] Attributes before migration: map[string]string{"data_json":"{\"hello\": \"world\"}", "path":"secret/test-123"}
2019/03/05 16:18:42 [DEBUG] Attributes after migration: map[string]string{"data_json":"{\"hello\": \"world\"}", "disable_read":"true", "path":"secret/test-123"}:
2019/03/05 16:18:42 [INFO] Found Vault Generic Secret state v0; migrating to v1
2019/03/05 16:18:42 [DEBUG] Attributes before migration: map[string]string{"allow_read":"false", "data_json":"{\"hello\": \"world\"}", "path":"secret/test-123"}
2019/03/05 16:18:42 [DEBUG] Attributes after migration: map[string]string{"allow_read":"false", "data_json":"{\"hello\": \"world\"}", "disable_read":"true", "path":"secret/test-123"}:
FAIL
FAIL    github.com/terraform-providers/terraform-provider-vault/vault   0.054s
make: *** [test] Error 1
```

It looks to me we would need to change our provider test to use "github.com/hashicorp/terraform/helper/schema" like https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/provider_test.go#L14

### CODE REVIEW

**Comment by dhohengassner** [comment]
@tyrannosaurus-becks was pretty annoying to update terraform to a current version using govendor 😉 

I think we would need some adjustments on the provider test - maybe something else afterwards

please review - input and help very appreciated

Thanks

**Comment by dhohengassner** [comment]
@tyrannosaurus-becks looks to me some go packages are missing for the pipeline - maybe you know how to solve that?

**Comment by cvbarros** [comment]
#321 will fix the `id` schema errors. I'd say park this until that one is merged then retry the tests.

**Comment by cvbarros** [comment]
Better wait for #356 , it will make it a lot easier to manage dependencies moving forward.

**Comment by dhohengassner** [comment]
@cvbarros thanks - I agree the change to go modules would be a nice improvment

saw the pain working with govendor... 😉 - hope the other PRs are merged soon

**Comment by dhohengassner** [comment]
will close this PR when we have a better solution merged

**Comment by tyrannosaurus-becks** [comment]
Hi @dhohengassner ! Thanks for working on this!

I notice tests aren't passing, and also it looks like `govendor` needs to be used to update the dependencies so that the changes are also reflected in `vendor.json`. We have some [Contribution Guidelines](https://github.com/terraform-providers/terraform-provider-vault/blob/master/.github/CONTRIBUTING.md) that give more detail on how to do that. Happy to review when it's ready to go.

**Comment by tyrannosaurus-becks** [comment]
Closing this, as its tests aren't passing and it's been inactive. Thanks for your efforts on it though!

**Pull request closed without merging**
