### PR TITLE
Allow update vault_auth_backend resource

### PR DESCRIPTION
**Pull request by leominov**
Should I add other fields from documentation?

It's about fixing #315 #290 #269
(ref: https://www.vaultproject.io/api/system/auth.html)

Let me know what you think about this changes.

### CODE REVIEW

**Comment by shwuandwing** [comment]
A lot of these parameters are already supported in the file "auth_mount.go".   Look at "vault_github_auth_backend.go" and "vault_jwt_auth_backend.go" on how to reuse it.

**Comment by leominov** [comment]
If we look at docs – `vault_approle_auth_backend_role` uses `vault_auth_backend`.

**Comment by shwuandwing** [comment]
I'm not sure what you mean about vault_approle_auth_backend_role?

vault_approle_auth_backend_role maps to /auth/approle/role/role_name (https://www.vaultproject.io/api/auth/approle/index.html#role_name)

vault_auth_backend maps to /sys/auth/:path/tune and /sys/auth/:path
https://www.vaultproject.io/api/system/auth.html#default_lease_ttl-1

The "tune" parameters are supported for various auth mounts already under auth_mount.go; can you not take advantage of that?

**Comment by yura-shutkin** [comment]
Good day, everyone.
I'm not familiar with go and I can't follow what's wrong with this PR
Right now there is a huge issue: If I change description of auth backend via this provider I will get new auth backend. I will loose every authorized token, every approle. It is not acceptable

This is plan output
Screenshot from 2019-10-10 12-09-29

This is expected error if I use vault_auth_mount, cause it is unknown resource
Screenshot from 2019-10-10 09-43-33

And this is what I get with this PR
Screenshot from 2019-10-10 12-15-32

**Comment by shwuandwing** [comment]
Oh, the max_ttl and default_lease_ttl_seconds parameters already existed.   This change is fine.   A future needs to refactor the max_ttl and default_lease_ttl_seconds into a tune block.

**Comment by tyrannosaurus-becks** [comment]
Closing due to lack of activity. Feel free to reopen it if you get a chance to circle back! Thank you!

**Pull request closed without merging**
